/**
 * The static search index, emitted at build from the same content the pages are
 * built from — so it cannot list a concept that does not exist, nor miss one
 * that does.
 *
 * An endpoint rather than a file in `public/`: `public/` is copied verbatim and
 * would have to be generated by a separate script and gitignored, which is a
 * second mechanism to keep in step. This is generated by the same build that
 * renders the pages, from the same import.
 *
 * Fetched on demand — when a reader opens search — never on page load. The
 * whole point of a concept page is that it paints without waiting for anything,
 * and an index in the critical path would trade that away for a feature most
 * readers never use on any given page.
 */
import type { APIRoute } from 'astro';
import { allNodes } from '../lib/content';
import { buildIndex } from '../lib/search';

export const GET: APIRoute = () => {
  const index = buildIndex(allNodes);
  const body = JSON.stringify(index);

  // #45 budgets roughly 30 KB. Printed rather than merely asserted: a budget
  // nobody sees is a budget nobody defends, and this is the number that decides
  // whether the client-side approach still makes sense as the graph grows.
  const kb = (Buffer.byteLength(body) / 1024).toFixed(1);
  console.log(`search index → ${index.length} concepts, ${kb} KB`);

  return new Response(body, {
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'public, max-age=300, s-maxage=3600',
    },
  });
};
